feat: add meeting link option
pkgjs/meet pull request #207
Opened 2024-11-21 22:44 UTC by bjohansebas

To avoid repeating a template due to a link change, the option to add a link is included, reducing template duplication with a simple link

2024-11-21 23:13 UTC, bjohansebas commented
I'll see if I can manage to pass the data option suggested in #206.

2024-11-22 00:21 UTC, jonchurch commented
This is actually a lot simpler for now though and is worth considering

it's reasonable to think someone would provide meeting link as a baseline for a meeting action

2024-11-22 00:24 UTC, jonchurch requested changes
Lets add it as a shorthand as well
https://github.com/pkgjs/meet#shorthand-in-your-custom-meeting-templates

Check the conversions.js file https://github.com/pkgjs/meet/blob/61042a30f295179c24673776877615fa12a6c0bc/lib/conversions.js#L13C1-L25C4

2024-11-22 00:24 UTC, jonchurch commented on action.yml
> +    description: 'A optional link to the join the meeting'
```suggestion
    description: 'An optional meeting join link'
```

2024-11-22 15:34 UTC, jonchurch approved these changes
lets update the default meeting template to use meetingLink if it is available

The notes default doesn't have a meeting link section, so no need there

https://github.com/pkgjs/meet/blob/main/lib/default-template.js#L42

2025-01-10 18:21 UTC, wesleytodd approved these changes
Yeah, I am a fan of simple defaults for this kind of stuff for sure.

2025-01-11 17:13 UTC, merged